default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: relay_dev

test:
  <<: *default
  database: relay_test

production:
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>
